name: Suggest a wallet
description: Suggest a new wallet to list on ethereum.org
title: Suggest a wallet
labels: ["wallet :purse:"]
body:
  - type: markdown
    attributes:
      value: |
        Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/). Only continue with the issue if the wallet meets the criteria listed there.
  - type: markdown
    id: project_info
    attributes:
      value: "## Project info"
  - type: input
    id: wallet_name
    attributes:
      label: Wallet name
      description: Please provide the official name of the wallet.
    validations:
      required: true
  - type: textarea
    id: wallet_description
    attributes:
      label: Wallet description
      description: Please provide a short 1-2 sentence description of the wallet. Avoid unsubstantiated marketing claims like “the best Ethereum wallet”.
    validations:
      required: true
  - type: textarea
    id: wallet_logo
    attributes:
      label: Wallet logo
      description: |
        Please provide an SVG or hi-res transparent PNG
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: input
    id: wallet_background
    attributes:
      label: Background color for brand logo
      description: Please provide a hex code for the brand color. This will be added to the background of the wallet card.
    validations:
      required: true
  - type: input
    id: wallet_url
    attributes:
      label: URL to the project
      description: Please provide a URL (e.g. to the website of the wallet).
    validations:
      required: true
  - type: input
    id: wallet_live_date
    attributes:
      label: When did the wallet go live to users?
      description: Please provide a date when the wallet was usable by the public
    validations:
      required: true
  - type: input
    id: wallet_active_development_team
    attributes:
      label: Does the wallet have an active development team?
      description: Are developers actively working on the wallet? Provide proof that the wallet is actively being worked on (ex. GitHub repo link).
    validations:
      required: true
  - type: input
    id: wallet_globally_accessible
    attributes:
      label: Is the wallet globally accessible?
      description: Please list any KYC requirements or geographic limitations of the wallet, if any exist.
    validations:
      required: true
  - type: input
    id: wallet_languages
    attributes:
      label: Is the wallet available in multiple languages?
      description: Please list languages that the wallet actively supports.
  - type: textarea
    id: wallet_socials
    attributes:
      label: What social links are there for the project?
      description: Please provide social links for the wallet (Discord, Twitter, etc.)
    validations:
      required: true
  - type: markdown
    id: device
    attributes:
      value: "## Device"
  - type: textarea
    id: wallet_mobile
    attributes:
      label: Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?
      description: Please provide app store links for the operating systems supported.
  - type: textarea
    id: wallets_desktop
    attributes:
      label: Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?
      description: Please provide links and information for the desktop operating systems supported.
  - type: textarea
    id: wallets_browser
    attributes:
      label: Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?
      description: Please provide links and information for the browsers that are supported.
  - type: textarea
    id: wallets_hardware
    attributes:
      label: Is it a hardware wallet?
      description: How does it broadcast signed transactions (e.g. USB, Bluetooth, QR code)?
