name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for creating your first issue! We encourage you to join our Discord server to collaborate with the Ethereum.org team & follow our latest updates: https://discord.gg/bTCfS8C'
        pr-message: 'Woohoo! Thanks for creating your first PR. We encourage you to join our Discord server to collaborate with the Ethereum.org team & follow our latest updates: https://discord.gg/bTCfS8C'
